[project]
name = "my-marimo-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo[recommended]>=0.18.4",
    "polars>=1.36.1",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.5.1",
    "ruff>=0.14.10",
]

[tool.ruff.lint]
select = ["E", "F", "I"]
